require 'rspec'
require 'edit_distance'

describe "Longest Common Subsequence Length" do
  it "should handle a tiny subsequence" do
    expect(lcs_length('AB', 'CB')).to be == 1
  end

  it "should handle a short subsequence" do
    expect(lcs_length('ABCD', 'XBCYDQ')).to be == 3
  end

  it "should handle a slightly harder case" do
    expect(lcs_length('ABCBDABB', 'BDCABAB')).to be == 5
  end
end

describe "Longest Common Subsequence" do
  it "should return the longest common subsequence" do
    expect(lcs('ABCBDAB', 'BDCABA')).to be == "BCBA"
  end

  it "should handle more complicated subsequences" do
    expect(lcs("levenshtein's algorithm", "frankenstein's monster")).to be == "enstein's or"
  end
end

describe "Edit Distance" do
  it "should calculate edit distance correctly for one letter" do
    expect(edit_distance('a', 'b')).to be == 1
  end

  it "should calculate edit distance for two characters" do
    expect(edit_distance('ab', 'ac')).to be == 1
    expect(edit_distance('ac', 'bc')).to be == 1
  end

  it "should calculate edit distance for three characters" do
    expect(edit_distance('abc', 'axc')).to be == 1
  end

  it "should calculate edit distance for medium strings (1)" do
    expect(edit_distance('xabxcdxxefxgx', '1ab2cd34ef5g6')).to be == 6
  end

  it "should calculate edit distance for medium strings (2)" do
    expect(edit_distance('xabxcdxxefxgx', 'abcdefg')).to be == 6
  end

  it "should calculate edit distance for medium strings (3)" do
    expect(edit_distance('javawasneat', 'scalaisgreat')).to be == 7
  end

  it "should calculate edit distance in tricky situations(1)" do
    expect(edit_distance('example', 'samples')).to be == 3
  end

  it "should calculate edit distance in tricky situations(2)" do
    expect(edit_distance('sturgeon', 'urgently')).to be == 6
  end

  it "should calculate edit distance in tricky situations(3)" do
    expect(edit_distance('levenshtein', 'frankenstein')).to be == 6
  end

  it "should calculate edit distance in tricky situations(4)" do
    expect(edit_distance('distance', 'difference')).to be == 5
  end

  it "should calculate edit distance in tricky situations(5)" do
    expect(edit_distance('因為我是中國人所以我會說中文', '因為我是英國人所以我會說英文')).to be == 2
  end

  it "should handle a large edit distance" do
    expect(edit_distance(
           'Morbi interdum ultricies neque varius condimentum. Donec ' +
           'volutpat turpis interdum metus ultricies vulputate. Duis ' +
           'ultricies rhoncus sapien, sit amet fermentum risus ' +
           'imperdiet vitae. Ut et lectus',
           'Duis erat dolor, cursus in tincidunt a, lobortis in odio. ' +
           'Cras magna sem, pharetra et iaculis quis, faucibus quis ' +
           'tellus. Suspendisse dapibus sapien in justo cursus'
     )).to be == 143
  end

  it "should handle the distance between the fucking human/chimpanzee genomes" do
    human_genome = "AGTAGCGTGAAGTGGTGAATTAATCCCTCACTGGTTCCTACGTGCGACAGTTTCCTGACCTTACAACGGACGAGTACATTGTTTTGTATGGGAGTGCGGCGTTTCACCGATCCTGGGGCGGCTATCCTGTGCGTCCGCAGGGCTCTCAGGTCGCATTCTCAAGAGGCGATATTTTGACAAAGTAGCGTTGGGGTGTCAGAAATCAAGTACTTGTCCGATTTTCTTACTGAGGCTTCTCTGATTTCCCAATCTACTTACGCGGGACGTGACTCTCAAAGTTGGATGTACCGCTCGGAACCAGCGCTGGACGTAGCTATATATCGCCATTTAAATTTGAGGCATTTATAAGGAACTTAGGTAAATAGATGGAACACAGCAGTCACTATAATAGTCGCAGAAGGCGTAGCGGACTCTCGTCATATACACGCTTGAAGAAAACCACTAAAATACCTAGGAGTGCCTGTAGCACTGTAGTCGTCGTCGACGGCGGATATAGTGGGGCCTTGGCTCGTAACTATCTTCGGACCTCGTCGCACCAACCCAGCTTAGTCCCCACGAGCGTCGAACCCTTGGGATGTTAGAGGGGGTGCATTCGACCGCATGAGAGCTGGAGTTTTTGCATCATCGCGCAGATACGGCGTTGGGCCGCCTTCTGCAGAGCCCTTCGTCTTGTTGACAACAGTATGAGCGATTAGCCTGGCGTCGTTTGGATGCCCAGTCTATGGACAAAATAAGCGAGGAAGCCCTGTGCGTTGCTCCCAAGACCCGGCCAGCGTGTAGAATTGTACAGAACAACGACTAGGCGTTGTCGATGTAAGAGTCCGTAACAAAGGCAGATTGGGAATAGCACTGGACCCCGCCTGAGTACTGTTGCACAGACGTAGCCGTTACCCCCAGCCCCAGGGGAAGCTGATGTTACGCCAGCCAGCATGGCTATGCGAGCAGGTCTCGTGGACCCAGTATGGACAAAACCGAAGGATAACAACTACACCAGGTGTCCACTTGTGGACAGTTCCCAATATATTCGGTGTTGTTTTTCTCCCTGTGCAATGCCATACCGATTAATCCGGAGTTGGGGGTACCGCGGCGCTACGGCTACCGCTATAGAATCTAAGTACGTGTCCGTTTTACCTGCATGGTCAGCGAAGGACTAACGTAGGATTAGGGGGAATTAACAAATATTATGTACAACATAGTGTTATCACTATCGCTAGATAACCATTAGAGTGAGTTCGGTAACGGCCCAGATGACGCGACCAGCTCCCAATTCTTCCGTGAGGCCAAGCACGCGCGTGTATGGGATGGTATAGATGTCTGGTTGTGGGGCTTTTTCCACAAAACCTGGGGCTGTGCGACAATACATGGGGCCTAGTTGGCTTGCCCGAGGAACGTGACCTCCCTGCAGGTTGCTAGATGCGAAGCTCTAGAAAAACAGTAATACCTACGTAGTGTCTCTATGAGATTACACGGACCTCACTTCAAGTTACGACGTGCGCAGAATGGACATCCTCAAGACACGAATGGTGATCACTAGGTACATTCACGCGGGTTCGAAGCCAAAAACAGCCCCGTACTGTGGCGATGCCCCGCATGCTGTATGGGATCAAATTATGCGGAAAATGTCAAGGGAGACGCGCAAATCGTCGGTCCCAGGTTGGGATTCATAGAATGCACTGGGATTCATCACACC"

    chimpanzee_genome = "AGTAGCGTGAAGTGGTGAATTACTCCCTCACTGGTTCCTACGTGCGACAGTTTCCTGACCTTACAACGGACGAGTACATTGTTTTGTATGGGAGTGCGGCGTCTCTCCGATCCTGGGGCGGCTATCCTGTGCGTCCGCAGGGCTCTCAGGTCGCATTCTCAAGAGGCGATATTTTGACAAAGTAGCGTTGGGGTGTCAGAAATCAAAGTACTTGTCCGATTTTCTTACTGAGGCTTCTCTGATTTCCCAATCTACTTACGCGGGACGTACTCTCAAAGTTGGATGTACCGCTCGGAACCAGCGCTGGACGTAGCTATATATCGCCATTTAAATTTGAGGCATTTATAAGGAACTTAGGTAAATAGATGGAACACAGCAGTCACTATAATAGTCGCAGGACGCGTAGCGGACTCTCGTCATATACACGCTTGAGGAAAAACATACATATACCTAGGAGTGCCTGTAGCACTGTAGTCGTCGTCGACGGCGGATATAGTGGGGCCTTGGCTCGTAACTATCTTCGGACCTCGTCGCACCAGACCCAGCTTAGTCCCCACGAGCGTCGAACCCTTGGGATGTTAGAGGAGGGTGCATTCGACCGCATGAGAGCTGGAGTTTTTGCATCATCGCGCAGATACGGCGTTGGGCCGCCTTCTGCAGAGCCCTTCGTCTTGTTGACAACAGTATGAGCGATTAGCCTGGCGTCGTTTGGATGCCCAGTCTATGGACAAAATAAGTGAGGAAGCCCTGTGCGTTGCTCCCAAGACCCGGCCAGCGTGTAGAATTGTACAGAACAACGACTAGGCGTTGTCGATGTAAGAGTCCGTAACAAAGGCAGATTGGGAATAGGCGTGGACCCCGCCTGAGTACTGTTGCACAGACGTACCCGTTACCCCCAGCCCCAGGGAAGCTGATGTTACGCCAGCCAGCATGGCTATGCGAGCAGGTCTCGTGGACCCAGTATGGACAAAACCGAAGGATAACAACTACACCAGGTGTCCACTTGTGGACAGTTCCCAATATATTCGGTGTTGTTTTTCTCCCTGTGCAATGCCATACCGATTAATCCGGAGTTGGGGGAACCGCGGCGCTACGGCTACCGCTATAGAATCTAAGTACGTGTCCGTTTTACCTGCATGGTCAGCGAAGGACTAACGTAGGATTAGGGGGAATTAACAAATATTATGTACAACATAGTGTTATCACTATCGCTAGATAACCATTAGAGTGAGTTCGGTAACGGCCCAGATGACGCGACAGCTCCCAATTCTTCCGTGAGGCCAAGCACGCGCGTGTATGGGATGGTATAGATGTCTGGTTGTGGGGCTTTTTCCACAAAACCTGGGGCTGTGTCGACAATACATGGGGCCTAGTTGGCTTGCCCGAGGAACGTGACCTCCCTGCAGGTTGCTAGATGCGAAGCTCTAGAAAAACAGTAATACCTACGTAGTGTCTCTATGAGATTACACGGACCTCACTTCAAGTTACGACGTGCGCAGAATGGACATCCTCAAGACACGAGATGGTGATCACTATTTACATTCACGCGGGTTCGAAGCCAAAAACAGCCCCGTACTGTGGCGATGCCCCGCATGCTGTATGGGATCAAATTATGCGGAAAATGTCAAGGGAGACGCGCAAATCGTCGGTCCCAAGGTTGGGATTCATAGAATGCACTGGATTCATCACC"

    expect(edit_distance(human_genome, chimpanzee_genome)).to be == 30
  end
end
